In [1]:
import torch 
from torch import nn
from torch.nn import functional as F

In [2]:
data = [[[1, 2, 3],[4, 5, 6],[7, 8, 9]]]
my_tensor = torch.tensor(data)
print(my_tensor)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [4]:
shape = (2,3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.rand(shape)
print(f"Random tensor: \n{random}\n")
print(f"Ones tensor: \n{ones}\n")
print(f"Zeros tensor: \n{zeros}\n")

print(shape)

Random tensor: 
tensor([[0.1079, 0.5541, 0.8686],
        [0.1176, 0.1931, 0.7349]])

Ones tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

(2, 3)


In [7]:
#mimicking like given a tensor of shape (2,3) we need another tensor of shape same .

template = torch.tensor([[1,2], [3,4]]) 

#random_tensor = torch.rand_like(template)
random_tensor = torch.randn_like(template , dtype = torch.float32)
print(f"Random tensor :  \n {random_tensor}\n")

Random tensor :  
 tensor([[-0.0522, -0.5971],
        [ 2.6770, -1.5432]])



In [ ]:
# Shape  , type and device 
## float32 are important for neural networks as they are used to calculate the gradients and update the weights of the model during training for learning .

tensor = torch.tensor([[2, 3]] , dtype = torch.float32 )

print(f"Shape of tensor : {tensor.shape}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"Device tensor is stored on : {tensor.device}")

Shape of tensor : torch.Size([1, 2])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


#### Autograd = pytorch automatic deferentiation engine that powers neural network training . It records all the operations that happen on a tensor and allows us to calculate gradients automatically when we call .backward() on a tensor .

In [17]:
x = torch.tensor([[[1, 2, 3], [4, 5, 6]]])
w = torch.tensor([[[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]] , requires_grad = True)

In [19]:
print(f"X : \n {x.requires_grad}\n")
print(f"W : \n {w.requires_grad}\n")

X : 
 False

W : 
 True

